import bcrypt from 'bcryptjs';
const data = {
    users: [
        {
          name: 'Tri Nguyen',
          email: 'admin@example.com',
          password: bcrypt.hashSync('1234', 8),
          isAdmin: true,
        },
        {
          name: 'John',
          email: 'user@example.com',
          password: bcrypt.hashSync('1234', 8),
          isAdmin: false,
        },
    ],
    products: [
        {
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'Product 1',
        },
        {
            name: 'Adidas Slim Shirt',
            category: 'pants',
            image: '/images/p2.jpg',
            price: 80,
            countInStock: 7,
            brand: 'Adidas',
            rating: 3.5,
            numReviews: 12,
            description: 'Product 2',
        },
        {
            name: 'Under Armour Slim Shirt',
            category: 'Shoes',
            image: '/images/p3.jpg',
            price: 150,
            countInStock: 99,
            brand: 'Under Armour',
            rating: 4,
            numReviews: 20,
            description: 'Product 3',
        },
        {
            name: 'Kappa Shirt',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 120,
            countInStock: 55,
            brand: 'Kappa',
            rating: 5,
            numReviews: 20,
            description: 'Product 4',
        },
        {
            name: 'Puma Ball',
            category: 'Ball',
            image: '/images/p5.jpg',
            price: 120,
            countInStock: 7,
            brand: 'Puma',
            rating: 3.5,
            numReviews: 30,
            description: 'Product 5',
        },
        {
            name: 'Asics Soccor',
            category: 'Soccor',
            image: '/images/p6.jpg',
            price: 250,
            countInStock: 100,
            brand: 'Asics',
            rating: 4.5,
            numReviews: 13,
            description: 'Product 6',
        },
    ],
};
export default data;