const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            catagory: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Slim Shirt',
            catagory: 'pants',
            image: '/images/p2.jpg',
            price: 80,
            brand: 'Adidas',
            rating: 3.5,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Under Armour Slim Shirt',
            catagory: 'Shoes',
            image: '/images/p3.jpg',
            price: 150,
            brand: 'Under Armour',
            rating: 4,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Kappa Shirt',
            catagory: 'Pants',
            image: '/images/p4.jpg',
            price: 120,
            brand: 'Kappa',
            rating: 5,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Puma Ball',
            catagory: 'Ball',
            image: '/images/p5.jpg',
            price: 120,
            brand: 'Puma',
            rating: 3.5,
            numReviews: 30,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Asics Soccor',
            catagory: 'Soccor',
            image: '/images/p6.jpg',
            price: 250,
            brand: 'Asics',
            rating: 4.5,
            numReviews: 13,
            description: 'high quality product',
        },
    ],
};
export default data;